// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avwtwmfdvszehjrpmqkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2d3R3bWZkdnN6ZWhqcnBtcWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MTQwMTQsImV4cCI6MjA3NTQ5MDAxNH0.SNwGv4vr2Gyo6UNCqcbZup3zycg4H97HW40MGKE523A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});